{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "C:\\Users\\zargham ahmad\\Desktop\\SiamFC-tf-master",
    "dependencies": [
      "numpy==1.17.2",
      "sacred==0.7.5",
      "tensorflow==2.0.0rc1"
    ],
    "mainfile": "train_siamese_model.py",
    "name": "SiamFC-3s-color-scratch",
    "repositories": [],
    "sources": [
      [
        "configuration.py",
        "_sources\\configuration_f2ba72f3fbe8a15c4e256306163a492e.py"
      ],
      [
        "siamese_model.py",
        "_sources\\siamese_model_d4cb57a78aed039eca89a644edeb3035.py"
      ],
      [
        "train_siamese_model.py",
        "_sources\\train_siamese_model_aba4d04d529258ab262a70d5ae499fc5.py"
      ],
      [
        "utils\\__init__.py",
        "_sources\\__init___d41d8cd98f00b204e9800998ecf8427e.py"
      ],
      [
        "utils\\misc_utils.py",
        "_sources\\misc_utils_2d2a00d8aa80cbfcda50ec7aa4b8e297.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\Public\\pythonfolder\\envs\\opencv-env\\lib\\site-packages\\wrapt\\wrappers.py\", line 564, in __call__\n    args, kwargs)\n",
    "  File \"C:\\Users\\Public\\pythonfolder\\envs\\opencv-env\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"experiments\\..\\train_siamese_model.py\", line 104, in main\n    model.build()\n",
    "  File \"experiments\\..\\siamese_model.py\", line 210, in build\n    self.build_inputs()\n",
    "  File \"experiments\\..\\siamese_model.py\", line 60, in build_inputs\n    self.dataloader = DataLoader(self.data_config, self.is_training())\n",
    "  File \"experiments\\..\\datasets\\dataloader.py\", line 56, in __init__\n    self.dataset_py = VID(config['input_imdb'], config['max_frame_dist'])\n",
    "  File \"experiments\\..\\datasets\\vid.py\", line 55, in __init__\n    with open(imdb_path, 'rb') as f:\n",
    "FileNotFoundError: [Errno 2] No such file or directory: 'data/train_imdb.pickle'\n"
  ],
  "heartbeat": "2019-09-29T19:37:32.342768",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",
    "hostname": "DESKTOP-A83M4BV",
    "os": [
      "Windows",
      "Windows-10-10.0.18362-SP0"
    ],
    "python_version": "3.6.9"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": true,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": "SiamFC-3s-color-scratch",
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-09-29T19:37:32.314842",
  "status": "FAILED",
  "stop_time": "2019-09-29T19:37:32.370443"
}